[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "torch-fem"
version = "0.4.5"
authors = [{ name = "Nils Meyer", email = "nils.meyer@uni-a.de" }]
description = "GPU accelerated differential finite elements for solid mechanics with PyTorch."
readme = "README.md"
license = {file = "LICENSE"}
keywords = ["finite elements", "automatic differentiation"]
requires-python = ">=3.10"
classifiers = [
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3.13',
]
dependencies = [
    "ipywidgets",
    "ipykernel",
    "matplotlib",
    "memory_profiler",
    "meshio",
    "meshzoo",
    "pyamg",
    "pyvista",
    "scipy",
    "tqdm",
    "torch",
    "trame",
    "trame-vuetify",
    "trame-vtk",
]

[project.urls]
source = "https://github.com/meyer-nils/torch-fem"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
torchfem = ["data/*.*"]
[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["win-64"]

[tool.pixi.pypi-dependencies]
torch-fem = { path = ".", editable = true }

[tool.pixi.tasks]
test = "python -m pytest"

[tool.pixi.dependencies]
python = "==3.12"
pytest = ">=8.4.2,<9"
testbook = ">=0.4.2,<0.5"
scipy = "<1.14"
pyamg = "<5.3.0"
